name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        uses: .github/workflows/build
      - name: Build iOS App
        run: flutter build ios --simulator
  build_android:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        uses: .github/workflows/build
      - name: Build Android App
        run: flutter build appbundle --debug