name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build iOS and Android Apps"
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - name: Install Dependency
        run: flutter pub get
      - name: Build iOS App
        run: flutter build ios --simulator
      - name: Build Android App
        run: flutter build appbundle --debug