name: Build App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Configure
        uses: ${{ github.action_path }}/build
      - name: Build iOS App
        run: flutter build ios --simulator
  build_android:
    runs-on: macos-latest
    steps:
      - name: Configure
        uses: ${{ github.action_path }}/build
      - name: Build Android App
        run: flutter build appbundle --debug